Repository jenkinsci/sonar-quality-gates-plugin, pull requests merged in 2024-08, with the labels that each got.

#27 update cd workflow
  .github/workflows/cd.yaml
Labels: chore

#28 Remove groupId from pom.xml
  pom.xml
Labels: chore

#29 Update Jenkins Security Scan action
  .github/workflows/jenkins-security-scan.yaml
Labels: chore

#30 Fix SECURITY-1523 / CVE-2020-2150
  src/main/java/org/quality/gates/jenkins/plugin/GlobalConfigDataForSonarInstance.java
  src/main/java/org/quality/gates/sonar/api/SonarHttpRequester.java
  src/main/java/org/quality/gates/sonar/api/SonarInstanceValidationService.java
  src/test/java/org/quality/gates/jenkins/plugin/BuildDecisionTest.java
Labels: bug, security

#35 Remove support for SonarQube versions 5.6 and 6.x
  README.md
  src/main/java/org/quality/gates/sonar/api/SonarHttpRequesterFactory.java
  src/main/java/org/quality/gates/sonar/api5x/SonarHttpRequester5x.java
  src/main/java/org/quality/gates/sonar/api60/SonarHttpRequester60.java
  src/main/java/org/quality/gates/sonar/api61/SonarHttpRequester61.java
Labels: documentation, removed

#36 Refactor and clean up code
  src/main/java/org/quality/gates/jenkins/plugin/BuildDecision.java
  src/main/java/org/quality/gates/jenkins/plugin/GlobalConfig.java
  src/main/java/org/quality/gates/jenkins/plugin/GlobalConfigDataForSonarInstance.java
  src/main/java/org/quality/gates/jenkins/plugin/GlobalConfigurationService.java
  src/main/java/org/quality/gates/jenkins/plugin/JobConfigData.java
  src/main/java/org/quality/gates/jenkins/plugin/JobConfigurationService.java
  src/main/java/org/quality/gates/jenkins/plugin/JobExecutionService.java
  src/main/java/org/quality/gates/jenkins/plugin/QGBuilder.java
  src/main/java/org/quality/gates/jenkins/plugin/QGBuilderDescriptor.java
  src/main/java/org/quality/gates/jenkins/plugin/QGPublisher.java
  src/main/java/org/quality/gates/jenkins/plugin/QGPublisherDescriptor.java
  src/main/java/org/quality/gates/jenkins/plugin/enumeration/BuildStatusEnum.java
  src/main/java/org/quality/gates/sonar/api/QualityGateResponseParser.java
  src/main/java/org/quality/gates/sonar/api/QualityGatesProvider.java
  src/main/java/org/quality/gates/sonar/api/QualityGatesStatus.java
  src/main/java/org/quality/gates/sonar/api/SonarHttpRequester.java
  src/main/java/org/quality/gates/sonar/api/SonarInstanceValidationService.java
Labels: chore
