Repository jenkinsci/sonar-quality-gates-plugin, pull requests merged in 2025-02, with the labels that each got.

#55 Fix sonar instance global config
  src/main/java/org/quality/gates/jenkins/plugin/GlobalSonarQualityGatesConfiguration.java
  src/main/java/org/quality/gates/jenkins/plugin/SonarInstance.java
  src/test/java/org/quality/gates/jenkins/plugin/BuildDecisionTest.java
Labels: bug

#54 Require Jenkins 2.479.1 or newer
  pom.xml
  src/main/java/org/quality/gates/jenkins/plugin/GlobalSonarQualityGatesConfiguration.java
  src/main/java/org/quality/gates/jenkins/plugin/QGPublisherDescriptor.java
  src/main/java/org/quality/gates/sonar/api/SonarHttpRequester.java
  src/test/java/org/quality/gates/jenkins/plugin/GlobalConfigTest.java
  src/test/java/org/quality/gates/sonar/api/QualityGateResponseParserTest.java
Labels: dependencies

#58 Fix sonar validation logic
  src/main/java/org/quality/gates/sonar/api/SonarInstanceValidationService.java
Labels: bugfix

#59 [JENKINS-75326] Improve api logging and fix issue caused by httpclient update
  src/main/java/org/quality/gates/sonar/api/ApiConnectionException.java
  src/main/java/org/quality/gates/sonar/api/SonarHttpRequester.java
  src/main/java/org/quality/gates/sonar/api/SonarHttpRequesterFactory.java
Labels: bugfix
